# -*- coding: utf-8 -*-
"""task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lP4mdQEzm92Xw0fsoxEoJyXdlZq5QAiI
"""

# Завдання 1
def caching_fibonacci():
    cache = {}
    def fibonacci(n):
        if n in cache:
            return cache[n]
        if n <= 0:
            return 0
        if n == 1:
            return 1
        cache[n] = fibonacci(n - 1) + fibonacci(n - 2)
        return cache[n]
    return fibonacci


fibonacci_cache = caching_fibonacci()
print(fibonacci_cache(8))